version: '3'
services:
  flourish:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: "postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@flourish-db:5432/postgres"
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - flourish-db
  flourish-db:
    image: timescale/timescaledb-ha:pg14-latest
    volumes:
      - timescaledb_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  timescaledb_volume: