openapi: '3.0.2'
info:
  title: Flourish
  version: '1.0'
servers:
  - url: https://{environment}.TODO:/v1
    variables:
      environment:
        default: api
        enum:
          - api       # Production
          - api.dev   # Development
paths:
  /user:
    post:
      tags:
        - Users
      description: Creates a new user
      # requestBody:
      #   required: true
        # content:
        #   application/json:
        #     schema:
        #       $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Request succeeded and a new user has been created
          headers:
            'Location':
              schema:
                type: string
                example: /user/15
              description: Location of newly created user resource

        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/AlreadyExists'

  /user/{id}:
    parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
    get:
      tags:
        - Users
      description: Gets information about a user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Users
      description: Updates a user
      responses:
        '204':
          description: OK. User updated
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Users
      description: Deletes a user
      responses:
        '204':
          description: OK. User deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'

  # TODO: query string for device type or state?
  /user/{id}/devices:
    get:
      tags:
        - Users
        - Device
      description: Lists all devices for a user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'

  /device:
    post:
      tags:
        - Device
      description: Creates a new device
      responses:
        '201':
          description: OK. New device created
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '422':
          description: Request contains invalid fields

  /device/{id}:
    get:
      tags:
        - Device
      description: Gets device information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Device
      description: Updates device information
      responses:
        '204':
          description: OK. Device updated
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Device
      description: Deletes device
      responses:
        '204':
          description: OK. Device deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'

  # TODO: query param time range
  /device/{id}/data:
    get:
      tags:
        - Device
      description: Gets sensor readings for specified period of time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorDataArray'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
        - Device
      description: Records new sensor reading
      responses:
        '200':
          description: OK
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          description: Device has sent too many requests (Rate limited)

  /device/{id}/metrics:
    get:
      tags:
        - Device
      description: Gets device metrics for specified period of time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceMetrics'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
        - Device
      description: Records new device metric
      responses:
        '200':
          description: OK
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/NoPermission'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          description: Device has sent too many requests (Rate limited)

components:
  responses:
    BadRequest:
      description: Server was unable to process request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NoPermission:
      description: User does not have permission to create/read/update/delete resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    AlreadyExists:
      description: Reesource already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Response:
      type: object
      properties:
        data:
          oneOf:
            - type: object
            - type: array
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: Common response object
    Error:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 401
        detail:
          type: string
          description: Additional information on why the request failed
          example: User not authorized to delete device
    User:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            id:
              type: integer
              description: User ID
            email:
              type: string
    Device:
      type: object
      properties:
        id:
          type: integer
          description: Device ID
        deviceType:
          type: string
          enum:
            - Sensor
            - Gateway
            - Other
          description: Device type
        deviceState:
          type: string
          enum:
            - Connected
            - Connecting
            - Disconnected
            - Error
          description: Last known state of the device
        api_version:
          type: string
          description: Flourish API version used by the device
        model:
          type: string
          description: Device model
          nullable: true
        software_version:
          type: string
          description: Software version of device
          nullable: true
    Devices:
      type: array
      description: An array of device objects
      items:
        $ref: '#/components/schemas/Device'
    SensorDataArray:
      type: array
      description: An array of device sensor readings
      items:
        $ref: '#/components/schemas/SensorData'
    SensorData:
      type: object
      properties:
        deviceId:
          type: integer
          description: Device ID
        time:
          type: string
          description: Timestamp of sensor reading
          nullable: true
          format: date-time
        temperature:
          type: number
          description: Air temperature in Celcius
          nullable: true
        humidity:
          type: number
          description: Relative air humidity
          nullable: true
        light:
          type: integer
          description: Light level in Lux
          nullable: true
        additional:
          type: object
          description: Additional sensor readings
    DeviceMetrics:
      type: array
      description: An array of device metrics
      items:
        $ref: '#/components/schemas/DeviceMetric'
    DeviceMetric:
      type: object
      properties:
        deviceId:
          type: integer
          description: Device ID
        time:
          type: string
          description: Timestamp of metric reading
          format: date-time
        battery_level:
          type: number
          description: Battery of device
          nullable: true
        cpu_usage:
          type: number
          description: CPU usage of device (in %)
          nullable: true
        memory_used:
          type: number
          description: Memory usage of device
          nullable: true
        memory_free:
          type: number
          description: Amount of free memory of device
          nullable: true
        additional:
          type: object
          description: Additional metrics