"""fixed_event_handler_cascade

Revision ID: 48eb54a47057
Revises: b99a35b2c64c
Create Date: 2022-05-11 17:33:25.681677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48eb54a47057'
down_revision = 'b99a35b2c64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_handlers_device_id_devices', 'event_handlers', type_='foreignkey')
    op.drop_constraint('fk_event_handlers_plant_id_plants', 'event_handlers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_handlers_plant_id_plants'), 'event_handlers', 'plants', ['plant_id'], ['plant_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_event_handlers_device_id_devices'), 'event_handlers', 'devices', ['device_id'], ['device_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_event_handlers_device_id_devices'), 'event_handlers', type_='foreignkey')
    op.drop_constraint(op.f('fk_event_handlers_plant_id_plants'), 'event_handlers', type_='foreignkey')
    op.create_foreign_key('fk_event_handlers_plant_id_plants', 'event_handlers', 'plants', ['plant_id'], ['plant_id'])
    op.create_foreign_key('fk_event_handlers_device_id_devices', 'event_handlers', 'devices', ['device_id'], ['device_id'])
    # ### end Alembic commands ###
