"""added user verified column

Revision ID: 68629c1abd4c
Revises: 48eb54a47057
Create Date: 2022-05-24 16:23:18.246776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68629c1abd4c'
down_revision = '48eb54a47057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_verified')
    # ### end Alembic commands ###
