"""VARCHAR_4_FIX

Revision ID: f0831db98083
Revises: 48eb54a47057
Create Date: 2022-05-12 21:10:09.360649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0831db98083'
down_revision = '48eb54a47057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
