openapi: '3.0.2'
info:
  title: Flourish
  version: '1.0'
servers:
  - url: https://{environment}.TODO:/{version}
    variables:
      environment:
        default: api
        enum:
          - api       # Production
          - api.dev   # Development
      version:
        default: v1
        enum:
          - v1

paths:
  /users:
    $ref: './components/paths/Users.yaml#/users'

  /users/login:
    $ref: './components/paths/Users.yaml#/users.login'

  /users/reset_password:
    $ref: './components/paths/Users.yaml#/users.reset_password'

  /users/reset_password/validate:
    $ref: './components/paths/Users.yaml#/users.reset_password.validate'

  /users/{user_id}:
    $ref: './components/paths/Users.yaml#/users.id'

  /users/{user_id}/verify:
    $ref: './components/paths/Users.yaml#/users.id.verify'

  /users/{user_id}/password:
    $ref: './components/paths/Users.yaml#/users.id.password'

  /users/{user_id}/preferences:
    $ref: './components/paths/Users.yaml#/users.id.preferences'

  # /users/{user_id}/logout:
  #   $ref: './components/paths/Users.yaml#/users.id.logout'

  /users/{user_id}/devices:
    $ref: './components/paths/Devices.yaml#/devices'

  /users/{user_id}/devices/{device_id}:
    $ref: './components/paths/Devices.yaml#/devices.device_id'

  # /users/{user_id}/devices/{device_id}/data:
  #   $ref: './components/paths/Devices.yaml#/devices.device_id.data'

  /users/{user_id}/devices/{device_id}/metrics:
    $ref: './components/paths/Devices.yaml#/devices.device_id.metrics'

  /users/{user_id}/plants:
    $ref: './components/paths/Plants.yaml#/plants'

  /users/{user_id}/plants/{plant_id}:
    $ref: './components/paths/Plants.yaml#/plants.plant_id'

  /users/{user_id}/plants/{plant_id}/data:
    $ref: './components/paths/Plants.yaml#/plants.plant_id.data'

  /users/{user_id}/plants/{plant_id}/overrides:
    $ref: './components/paths/Plants.yaml#/plants.plant_id.overrides'

  /users/{user_id}/plants/{plant_id}/overrides/{override_id}:
    $ref: './components/paths/Plants.yaml#/plants.plant_id.overrides.override_id'

  /users/{user_id}/alerts:
    $ref: './components/paths/Alerts.yaml#/alerts'

  /users/{user_id}/alerts/view:
    $ref: './components/paths/Alerts.yaml#/alerts.view'

  /users/{user_id}/alerts/{alert_id}:
    $ref: './components/paths/Alerts.yaml#/alerts.alert_id'

  /users/{user_id}/collections:
    $ref: './components/paths/Collections.yaml#/collections'

  /users/{user_id}/collections/{collection_id}:
    $ref: './components/paths/Collections.yaml#/collections.collection_id'

  /users/{user_id}/collections/{collection_id}/add:
    $ref: './components/paths/Collections.yaml#/collections.collection_id.add'

  /users/{user_id}/collections/{collection_id}/remove:
    $ref: './components/paths/Collections.yaml#/collections.collection_id.remove'

  /plants:
    $ref: './components/paths/PlantTypes.yaml#/plants'

  /plants/{plant_type_id}:
    $ref: './components/paths/PlantTypes.yaml#/plants.plant_type_id'

components:
  responses:
    $ref: './components/responses/index.yaml'
  parameters:
    $ref: './components/parameters/index.yaml'
  schemas:
    $ref: './components/schemas/index.yaml'
  headers:
    $ref: './components/headers/index.yaml'

  securitySchemes:
    name:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://domain.test/api/oauth/dialog
          tokenUrl: https://domain.test/api/oauth/token
          scopes:
            read: example read scope
            write: example write scope

